name: Deploy

on:
  push:
    branches:
      - master

jobs:
  # GitHub Pagesへのデプロイ
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: setup node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: install
        run: npm install

      - name: build
        run: npm run build
        # ビルドする際に各APIをコールするので、APIトークンをSecretsに登録しておく必要がある
        # env:
          # GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
          # QIITA_API_TOKEN: ${{ secrets.QIITA_API_TOKEN }}

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.3.2
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public